### ISSUE TITLE
Attempting to create a thread without a verified tripcode returns a 500 error, should maybe explain problem to user instead?

### ISSUE THREAD

**Issue by amenbabylon** [lily-mayfield/soyboard#12] opened 2018-04-22 09:00 UTC
I'm not actually sure if this should be an "issue," but it seemed like a better place to put it than buried in a thread.

**Comment by lily-mayfield** [comment] 2018-04-23 07:52
duplicate of #6 but also thank you @amenbabylon for bringing this up here--I super appreciate it when people bring up ideas/usability problems/etc in the issues! Even though this is a duplicate I still really appreciate the effort!

Thanks!

**Closed** 2018-04-23 07:52 UTC
Labels: duplicate
